apiVersion: apps/v1

kind: Deployment

metadata:

  name: site-deployment

  labels:

    app: web-site

spec:

  replicas: 3

  selector:

    matchLabels:

      app: web-site

  template:

    metadata:

      labels:

        app: web-site

    spec:

      containers:

      - name: web-site

        image: mahesh8887/site:latest

        ports:

        - containerPort: 80
